# Generated by Django 4.2.11 on 2026-05-24 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import maasserver.models.cleansave


class Migration(migrations.Migration):

    dependencies = [
        ('maasserver', '0343_goodbye_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiBootDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_os_index', models.IntegerField(default=0, help_text='Index (by priority order) of the OS that boots by default.')),
                ('boot_timeout', models.IntegerField(default=5, help_text='GRUB menu timeout in seconds before booting the default OS.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this deployment was first created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this deployment was last modified.')),
            ],
            options={
                'verbose_name': 'multi-boot deployment',
                'verbose_name_plural': 'multi-boot deployments',
                'db_table': 'maasserver_multibootdeployment',
            },
        ),
        migrations.CreateModel(
            name='MultiBootOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osystem', models.CharField(help_text="Operating system type, e.g. 'ubuntu', 'centos', 'windows'.", max_length=31)),
                ('distro_series', models.CharField(help_text="Distribution series, e.g. 'jammy', 'noble', 'win2022'.", max_length=31)),
                ('hwe_kernel', models.CharField(blank=True, help_text="HWE kernel flavor, e.g. 'hwe-22.04'. Optional.", max_length=31)),
                ('architecture', models.CharField(blank=True, help_text="Architecture, e.g. 'amd64/generic'. Optional.", max_length=31)),
                ('priority', models.IntegerField(default=0, help_text='Boot menu order (0 = first, highest priority). Must be unique within a deployment.')),
                ('boot_disk', models.ForeignKey(blank=True, help_text='Which physical disk this OS installs to. Null = auto-detect.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maasserver.physicalblockdevice')),
                ('deployment', models.ForeignKey(help_text='Parent deployment this OS entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='oses', to='maasserver.multibootdeployment')),
            ],
            options={
                'verbose_name': 'multi-boot OS entry',
                'verbose_name_plural': 'multi-boot OS entries',
                'db_table': 'maasserver_multibootos',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='bootresource',
            name='last_deployed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bootsource',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority value. Higher values mean higher priority. Must be non-negative.', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bootsource',
            name='skip_keyring_verification',
            field=models.BooleanField(default=0, help_text='If true, keyring signature verification will be skipped.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='current_deployment_script_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maasserver.scriptset'),
        ),
        migrations.AddField(
            model_name='nodeuserdata',
            name='for_ephemeral_environment',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodeuserdata',
            name='node',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='maasserver.node'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_type',
            field=models.IntegerField(choices=[(0, 'Commissioning script'), (2, 'Testing script'), (3, 'Release script'), (4, 'Deployment script')], default=2),
        ),
        migrations.AlterField(
            model_name='scriptset',
            name='result_type',
            field=models.IntegerField(choices=[(0, 'Commissioning'), (1, 'Installation'), (2, 'Testing'), (3, 'Release'), (4, 'Deployment')], default=0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='nodeuserdata',
            unique_together={('node', 'for_ephemeral_environment')},
        ),
        migrations.AlterModelTable(
            name='bootsourceselection',
            table='maasserver_bootsourceselectionlegacy',
        ),
        migrations.CreateModel(
            name='MultiBootPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_point', models.CharField(help_text="Mount point, e.g. '/', '/boot', '/boot/efi'.", max_length=255)),
                ('size', models.BigIntegerField(help_text='Partition size in bytes.')),
                ('fstype', models.CharField(help_text="Filesystem type, e.g. 'ext4', 'fat32', 'xfs', 'ntfs'.", max_length=31)),
                ('os_entry', models.ForeignKey(help_text='Parent OS entry this partition belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='maasserver.multibootos')),
            ],
            options={
                'verbose_name': 'multi-boot partition',
                'verbose_name_plural': 'multi-boot partitions',
                'db_table': 'maasserver_multibootpartition',
            },
        ),
        migrations.AddField(
            model_name='multibootdeployment',
            name='node',
            field=models.OneToOneField(help_text='The machine this deployment belongs to. One-to-one.', on_delete=django.db.models.deletion.CASCADE, related_name='multi_boot_deployment', to='maasserver.node'),
        ),
        migrations.CreateModel(
            name='ImageManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest', models.JSONField()),
                ('boot_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maasserver.bootsource')),
            ],
        ),
        migrations.CreateModel(
            name='BootSourceSelectionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('os', models.CharField(blank=True, default='', help_text='The operating system for which to import resources.', max_length=20)),
                ('release', models.CharField(blank=True, default='', help_text='The OS release for which to import resources.', max_length=20)),
                ('arch', models.TextField()),
                ('boot_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maasserver.bootsource')),
                ('legacy_selection', models.ForeignKey(db_column='legacyselection_id', on_delete=django.db.models.deletion.CASCADE, to='maasserver.bootsourceselection')),
            ],
            options={
                'db_table': 'maasserver_bootsourceselection',
            },
            bases=(maasserver.models.cleansave.CleanSave, models.Model),
        ),
        migrations.AddField(
            model_name='bootresource',
            name='boot_source_selection',
            field=models.ForeignKey(db_column='selection_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='maasserver.bootsourceselectionnew'),
        ),
        migrations.AddConstraint(
            model_name='multibootpartition',
            constraint=models.UniqueConstraint(fields=('os_entry', 'mount_point'), name='uq_multibootpartition_osentry_mountpoint'),
        ),
        migrations.AddConstraint(
            model_name='multibootos',
            constraint=models.UniqueConstraint(fields=('deployment', 'priority'), name='uq_multibootos_deployment_priority'),
        ),
        migrations.AlterUniqueTogether(
            name='bootsourceselectionnew',
            unique_together={('boot_source', 'os', 'release', 'arch')},
        ),
    ]
