"""add multiboot models

Revision ID: 0021
Revises: 0020
Create Date: 2026-05-27 04:56:27.207214+00:00

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: str | None = '0020'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maasserver_multibootdeployment',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('default_os_index', sa.Integer(), nullable=False),
    sa.Column('boot_timeout', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['maasserver_node.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('maasserver_multibootos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('osystem', sa.String(length=31), nullable=False),
    sa.Column('distro_series', sa.String(length=31), nullable=False),
    sa.Column('hwe_kernel', sa.String(length=31), nullable=True),
    sa.Column('architecture', sa.String(length=31), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.BigInteger(), nullable=False),
    sa.Column('boot_disk_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['boot_disk_id'], ['maasserver_blockdevice.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['maasserver_multibootdeployment.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', 'priority')
    )
    op.create_index('maasserver_multibootos_deployment_id', 'maasserver_multibootos', ['deployment_id'], unique=False)
    op.create_table('maasserver_multibootpartition',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('mount_point', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('fstype', sa.String(length=31), nullable=False),
    sa.Column('os_entry_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['os_entry_id'], ['maasserver_multibootos.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('os_entry_id', 'mount_point')
    )
    op.create_index('maasserver_multibootpartition_os_entry_id', 'maasserver_multibootpartition', ['os_entry_id'], unique=False)
    # op.create_index('maasserver_bootsourceselection_boot_source_id_b911aa0f', 'maasserver_bootsourceselection', ['boot_source_id'], unique=False)
    # op.drop_index('maasserver_node_current_deployment_script_set_id_0013', table_name='maasserver_node')
    # op.drop_constraint('maasserver_oidcrevokedtoken_user_email_fkey', 'maasserver_oidcrevokedtoken', type_='foreignkey')
    # op.create_foreign_key(None, 'maasserver_oidcrevokedtoken', 'auth_user', ['user_email'], ['username'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'maasserver_oidcrevokedtoken', type_='foreignkey')
    # op.create_foreign_key('maasserver_oidcrevokedtoken_user_email_fkey', 'maasserver_oidcrevokedtoken', 'auth_user', ['user_email'], ['username'], initially='DEFERRED', deferrable=True)
    # op.create_index('maasserver_node_current_deployment_script_set_id_0013', 'maasserver_node', ['current_deployment_script_set_id'], unique=False)
    # op.drop_index('maasserver_bootsourceselection_boot_source_id_b911aa0f', table_name='maasserver_bootsourceselection')
    op.drop_index('maasserver_multibootpartition_os_entry_id', table_name='maasserver_multibootpartition')
    op.drop_table('maasserver_multibootpartition')
    op.drop_index('maasserver_multibootos_deployment_id', table_name='maasserver_multibootos')
    op.drop_table('maasserver_multibootos')
    op.drop_table('maasserver_multibootdeployment')
    # ### end Alembic commands ###
