"""add_multiboot_partition timestamps

Revision ID: 0022
Revises: 0021
Create Date: 2026-06-05 20:12:46.423835+00:00

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0022'
down_revision: str | None = '0021'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_index('maasserver_bootsourceselection_boot_source_id_b911aa0f', 'maasserver_bootsourceselection', ['boot_source_id'], unique=False)
#     op.add_column('maasserver_multibootpartition', sa.Column('created', sa.DateTime(timezone=True), nullable=False))
#     op.add_column('maasserver_multibootpartition', sa.Column('updated', sa.DateTime(timezone=True), nullable=False))
#     op.drop_index('maasserver_node_current_deployment_script_set_id_0013', table_name='maasserver_node')
#     op.drop_constraint('maasserver_oidcrevokedtoken_user_email_fkey', 'maasserver_oidcrevokedtoken', type_='foreignkey')
#     op.create_foreign_key(None, 'maasserver_oidcrevokedtoken', 'auth_user', ['user_email'], ['username'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
#     # ### end Alembic commands ###
#
#
# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'maasserver_oidcrevokedtoken', type_='foreignkey')
#     op.create_foreign_key('maasserver_oidcrevokedtoken_user_email_fkey', 'maasserver_oidcrevokedtoken', 'auth_user', ['user_email'], ['username'], initially='DEFERRED', deferrable=True)
#     op.create_index('maasserver_node_current_deployment_script_set_id_0013', 'maasserver_node', ['current_deployment_script_set_id'], unique=False)
#     op.drop_column('maasserver_multibootpartition', 'updated')
#     op.drop_column('maasserver_multibootpartition', 'created')
#     op.drop_index('maasserver_bootsourceselection_boot_source_id_b911aa0f', table_name='maasserver_bootsourceselection')
#     # ### end Alembic commands ###
def upgrade() -> None:
    # 2. ONLY these two columns stay (Changed nullable to True so existing data doesn't crash)
    op.add_column('maasserver_multibootpartition', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('maasserver_multibootpartition', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    # ONLY these two lines stay to revert your specific columns if needed
    op.drop_column('maasserver_multibootpartition', 'updated')
    op.drop_column('maasserver_multibootpartition', 'created')
