# Copyright 2025 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from datetime import datetime
from typing import Union

from pydantic import Field

from maasservicelayer.models.base import ResourceBuilder, UNSET, Unset


class MultiBootDeploymentBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    boot_timeout: Union[int, Unset] = Field(default=UNSET, required=False)
    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    default_os_index: Union[int, Unset] = Field(default=UNSET, required=False)
    node_id: Union[int, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)


class MultiBootOSBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    architecture: Union[str, None, Unset] = Field(
        default=UNSET, required=False
    )
    boot_disk_id: Union[int, None, Unset] = Field(
        default=UNSET, required=False
    )
    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    deployment_id: Union[int, Unset] = Field(default=UNSET, required=False)
    distro_series: Union[str, Unset] = Field(default=UNSET, required=False)
    hwe_kernel: Union[str, None, Unset] = Field(default=UNSET, required=False)
    osystem: Union[str, Unset] = Field(default=UNSET, required=False)
    priority: Union[int, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)


class MultiBootPartitionBuilder(ResourceBuilder):
    """Autogenerated from utilities/generate_builders.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    created: Union[datetime, Unset] = Field(default=UNSET, required=False)
    fstype: Union[str, Unset] = Field(default=UNSET, required=False)
    mount_point: Union[str, Unset] = Field(default=UNSET, required=False)
    os_entry_id: Union[int, Unset] = Field(default=UNSET, required=False)
    size: Union[int, Unset] = Field(default=UNSET, required=False)
    updated: Union[datetime, Unset] = Field(default=UNSET, required=False)
